### ISSUE TITLE
ItemRack sets are not seperated by individual set

### ISSUE THREAD

**Issue by MakeTheFuture** [DJSchaffner/BetterBags_ItemRack#2]
Just logging an issue here to show the dev that this is considered by the community an issue. We've been told to move from AdiBag to BetterBags. We have, and our sets are all grouped together with just a note on BetterBags ItemRack to say you 'might' add it in the future. I'm not sure why this is the case and it's not assumed to be a necessary feature to mimmic the base feature set of AdiBag ItemRack. 

Most of the over 1.3K+ users who have moved most likely do not have a GitHub account, so I thought I'd jump in here to show you it's very much needed, and we would appreciate any time and attention you can give it, please.

**Comment by DJSchaffner** [comment]
It is already being worked on here #1 😄 
There are just a few last issues to iron out and potentially talk to BetterBags dev about some upcoming features that would be helpful in the long run to see if it makes sense to wait those out or implement a temporary solution.

**Comment by DJSchaffner** [comment]
Release will probably happen later tonight if no major issues come up.

**Comment by DJSchaffner** [comment]
Changes have been released and should implement the requested features. If any problems arise feel free to open another ticket
