### ISSUE TITLE
Item sets dissapear when swaping sets

### ISSUE THREAD

**Issue by fekke** [DJSchaffner/BetterBags_ItemRack#4]
![betterbags_itemrack_problem_01](https://github.com/DJSchaffner/BetterBags_ItemRack/assets/3190732/fb5d7fa4-d46b-4c3a-b1ee-a7eec727bc3f)

When swapping sets, you cant see items in bag. 
When you select "show bags" you can see the items. And then turning off "show bags" you can then see the items again. 

Using version 0.1.21 of Betterbags and 1.4.0 of BetterbagsItemrack and itemrack-classic 3.77.

**Comment by DJSchaffner** [comment]
This seems to be a problem on the end of [BetterBags](https://github.com/Cidan/BetterBags).
At the time of swapping gear this, addon does not interfere with what happens inside the bags.
