### ISSUE TITLE
LUA error during using new BetterBags + Itemrack plugin.

### ISSUE THREAD

**Issue by omggga** [DJSchaffner/BetterBags_ItemRack#5]
Looks like Betterbags updated some core functions, right now i am getting lua error during character load.

![image](https://github.com/user-attachments/assets/daa40823-f985-4230-b3e1-b57751dbd21b)

Also when changing items by hotkey with Itemrack the category still appears.

Here i equipped FIREDPS set, but the empty category still exist even i open and close bags.

![image](https://github.com/user-attachments/assets/8f1eb4a9-6bdc-4cad-928d-4062a839bba2)

**Comment by DJSchaffner** [comment]
Thanks for the report, I will take a look at this

**Comment by DJSchaffner** [comment]
I pushed an update where this should be fixed. Will be available as soon as CurseForges approves it. Alternatively you can manually replace it with the files from the repo if it's urgent

**Comment by omggga** [comment]
Many thanks! :)
